<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKMRakzH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKMRakzH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKMRakzH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKMRakzH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKMRakzH\App_KernelDevDebugContainer([
    'container.build_hash' => 'KMRakzH',
    'container.build_id' => '23d746ad',
    'container.build_time' => 1681154338,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKMRakzH');
