<?php

namespace ContainerKMRakzH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VGkhT8qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vGkhT8q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vGkhT8q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movieQuote' => ['privates', '.errored..service_locator.vGkhT8q.App\\Entity\\MovieQuote', NULL, 'Cannot autowire service ".service_locator.vGkhT8q": it references class "App\\Entity\\MovieQuote" but no such service exists.'],
            'movieQuoteRepository' => ['privates', 'App\\Repository\\MovieQuoteRepository', 'getMovieQuoteRepositoryService', true],
        ], [
            'movieQuote' => 'App\\Entity\\MovieQuote',
            'movieQuoteRepository' => 'App\\Repository\\MovieQuoteRepository',
        ]);
    }
}
