<?php

namespace ContainerGenyTjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ENnrd35Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ENnrd35' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ENnrd35'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movieQuoteRepository' => ['privates', 'App\\Repository\\MovieQuoteRepository', 'getMovieQuoteRepositoryService', true],
        ], [
            'movieQuoteRepository' => 'App\\Repository\\MovieQuoteRepository',
        ]);
    }
}
