<?php

namespace ContainerGenyTjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FEbFtr4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FEbFtr4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FEbFtr4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movieQuote' => ['privates', '.errored..service_locator.FEbFtr4.App\\Entity\\MovieQuote', NULL, 'Cannot autowire service ".service_locator.FEbFtr4": it references class "App\\Entity\\MovieQuote" but no such service exists.'],
        ], [
            'movieQuote' => 'App\\Entity\\MovieQuote',
        ]);
    }
}
