<?php

namespace ContainerGenyTjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovieQuote2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vGkhT8q.App\Entity\MovieQuote' shared service.
     *
     * @return \App\Entity\MovieQuote
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vGkhT8q": it references class "App\\Entity\\MovieQuote" but no such service exists.');
    }
}
